name: mikepage-dev
recipe: laravel
config:
  webroot: public/
  php: "8.5"
  via: nginx
  xdebug: coverage
services:
  mailpit:
    type: mailpit
    mailFrom:
      - appserver
proxy:
  mailpit:
    - mail.mikepage-dev.lndo.site
